accounts/urls.py
from django.conf.urls import url

from . import views

app_name='accounts'

urlpatterns=[
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout')
]

demo/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework import routers
from . import views
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static


routers=routers.DefaultRouter()
routers.register('plantas_registradas', views.PlantaViewset)
routers.register('BD', views.BDViewset)
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include(routers.urls)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('pages.urls')),

]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.conf.urls import url

from . import views

app_name='pages'

urlpatterns=[
    url(r'^nova_planta/$', views.nova_planta, name='nova_planta'),
    url(r'^qrcode/$', views.qrcode, name='qrcode'),
    url(r'^minhas_plantas/$', views.minhas_plantas, name='minhas_plantas'),
    url(r'^banco_de_dados/$', views.banco_de_dados),
    url(r'^apagar/$', views.apagar),
    url(r'^deletar/$', views.deletar),
    url(r'^dados_planta/$', views.dados_planta),
    url(r'^informacoes/$', views.informacoes),
]

accounts/models.py
from django.db import models

# Create your models here.

demo/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User


# Create your models here.
class Planta(models.Model):
    name=models.CharField(max_length=300, unique=True, blank=False)
    species=models.CharField(max_length=300,blank=False, unique=False)
    date=models.DateField(default=datetime.date(datetime.today()))
    image=models.ImageField(upload_to='Images', default='planta.png', blank=True, null=True)
    incidencia_solar=models.CharField(max_length=256, default='Sem dados')
    regada=models.DateField(default=datetime.date(datetime.today()))
    temperatura=models.CharField(max_length=256, default='Sem dados')
    umidade=models.CharField(max_length=256, default='Sem dados')
    usuario=models.ForeignKey(User, default=None,on_delete=models.CASCADE)



class BD(models.Model):
    nome_comum=models.CharField(max_length=256, blank=False)
    nome_especie=models.CharField(max_length=256, blank=False)
    temperatura= models.CharField(max_length=30, default='25 °C')
    sol_horas=models.IntegerField(default=1)
    rega_dias=models.IntegerField(default=1)
    obs=models.CharField(max_length=256, default='Sem informações adicionais', blank=False)

pages/models.py
from django.db import models

# Create your models here.

pages/forms.py
from django import forms
from demo import models

class NovaPlanta(forms.ModelForm):
    class Meta:
        model=models.Planta
        fields=['name','species','date','image']

class RegarPlanta(forms.ModelForm):
    class Meta:
        model=models.Planta
        fields=['regada']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            #log the user in
            login(request,user)
            return redirect('pages:minhas_plantas')

    else:
        form=UserCreationForm()

    return render(request,'accounts/signup.html', {'form': form})


def login_view (request):
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user
            user= form.get_user()
            login(request, user)
            return redirect('pages:minhas_plantas')
    else:
        form=AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('pages:minhas_plantas')
    return render(request,'accounts/logout.html')

demo/views.py
from django.shortcuts import render
from rest_framework import viewsets
from .serializers import PlantaSerializer, BDSerializer
from .models import Planta ,BD
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.shortcuts import render
# Create your views here.

def superuser_required():
    def wrapper(wrapped):
        class WrappedClass(UserPassesTestMixin, wrapped):
            def test_func(self):
                return self.request.user.is_superuser

        return WrappedClass
    return wrapper


@superuser_required()
class PlantaViewset(LoginRequiredMixin,viewsets.ModelViewSet):
    login_url = '/accounts/login'
    serializer_class = PlantaSerializer
    queryset = Planta.objects.all()


@superuser_required()
class BDViewset(LoginRequiredMixin, viewsets.ModelViewSet):
    login_url = '/accounts/login'
    serializer_class = BDSerializer
    queryset = BD.objects.all()

pages/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from demo.models import Planta,BD
from . import forms
from datetime import date

# Create your views here.

def restart_plantas():
    global planta_name
    planta_name = ''
    global planta_especie
    planta_especie = ''
    global usuario
    usuario = ''

@login_required(login_url='/accounts/login')
def qrcode(request):
    return render(request,'qrcode.html', {'planta': planta_name, 'especie':planta_especie, 'usuario': usuario})

@login_required(login_url='/accounts/login')
def home_page(request):
    restart_plantas()
    return render(request,'login.html')

@login_required(login_url='/accounts/login')
def minhas_plantas(request):
    restart_plantas()

    minhas_plantas=Planta.objects.all().filter(usuario=request.user)
    return render(request,'minhas_plantas.html', {'plantas':minhas_plantas ,'user':request.user})

@login_required(login_url='/accounts/login')
def banco_de_dados(request):
    restart_plantas()
    bd=BD.objects.all()
    return render(request,'banco_de_dados.html', {'bd': bd})

@login_required(login_url='/accounts/login')
def dados_planta(request):
    restart_plantas()
    global name
    name=request.COOKIES.get('data')
    planta=Planta.objects.all().filter(name=request.COOKIES.get('data'))

    species=''
    for plant in planta:
        species=plant.species
    bd=BD.objects.all().filter(nome_comum=species)

    if len(planta)!=0:
        plant=Planta.objects.get(name=name)
        if request.method == 'POST':
            form = forms.RegarPlanta(request.POST, instance=plant)
            if form.is_valid():
                form.save()

            else:
                return render(request, 'nova_planta.html', {'message': 'Dados inválidos'})
        else:
            form = forms.RegarPlanta()

        return render(request,'dados_planta.html', {'planta': planta, 'form':form, 'bd': bd})
    else:
        return render(request, 'dados_planta.html')

@login_required(login_url='/accounts/login')
def informacoes(request):
    restart_plantas()

    return render(request,'informacoes.html')

@login_required(login_url='/accounts/login')
def apagar(request):
    minhas_planta=Planta.objects.filter(usuario=request.user).delete()

    return render(request,'apagar.html', {'planta': minhas_planta})

@login_required(login_url='/accounts/login')
def deletar(request):
    planta_deletada=Planta.objects.all().filter(name=name).delete()
    return render(request,'deletar.html', {'deletada': planta_deletada})

@login_required(login_url='/accounts/login')
def nova_planta(request):
    restart_plantas()
    bd = BD.objects.all()
    if request.method=='POST':
        form=forms.NovaPlanta(request.POST,request.FILES)
        if form.is_valid():
            #save plant to db
            instance=form.save(commit=False)
            global planta_name
            planta_name=instance.name
            global planta_especie
            planta_especie=instance.species
            global usuario
            usuario=request.user
            instance.usuario=request.user
            instance.save()
            return redirect('pages:qrcode')
        else:
            return render(request,'nova_planta.html', {'message': 'Dados inválidos'})
    else:
        form = forms.NovaPlanta()
    return render(request,'nova_planta.html', {'form': form ,'bd': bd})

templates/accounts/login.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clarissa - sistema de IoT para monitoramento e cuidado de plantas caseiras</title>
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/minhas_plantas.css">
    <link rel="stylesheet" href="/static/login.css">
</head>
<body>
    <div id="navbar">
        <div id="nav">
            <h1>Clarissa</h1>
        </div>
        <div id="left_bar">
 
            <p>
                <a href="/accounts/login" class="page">Login</a>
            </p>
            
            <p>
                <a href="/accounts/signup" >Criar conta</a>
            </p>
            
        </div>
        <div id="bottom_left"></div>
        
    </div>

    <div id="container" class="box">
        <div id="small_table">
            <h2 style="margin-top: 1rem;">Para acessar nossos serviços faça login ou crie uma nova conta de usuário</h2>
            <form id="site-form" method="POST" action="/accounts/login/">
                {% csrf_token %}
                {{form}}
                <p>
                    <input class="login_btn" type="submit" value="Login" onclick="saveUser()">
                </p>
                
            </form>
    </div>
    

    <script src="/static/login.js"></script>
   
</body>
</html>

templates/accounts/logout.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clarissa - sistema de IoT para monitoramento e cuidado de plantas caseiras</title>
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/minhas_plantas.css">
    <link rel="stylesheet" href="/static/logout.css">
</head>
<body>
    <div id="navbar">
        <div id="nav">
            <h1>Clarissa</h1>
        </div>
        <div id="left_bar">
            <a href="/nova_planta">Cadastrar nova planta </a>
            <p>
                <a href="/minhas_plantas" >Minhas plantas </a>
            </p>
            
            <p>
                <a href="/banco_de_dados">Banco de dados </a>
            </p>

            <p>
                <a href="/informacoes">Informações do sistema</a>
            </p>

            <p>
                <a href="/accounts/logout" class="page">Sair</a>
            </p>
            
        </div>
        <div id="bottom_left"></div>
        
    </div>

    <div id="container" class="box">
        <div id="small_table">
            <h2 style="margin-top: 1rem;">Clique aqui para sair</h2>
            <h3 style="margin-top: 1rem;">Esperamos que você volte logo... </h3>
            <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <button class='submit_btn'type="submit">Logout</button>
            </form>
        </div>
            
    </div>
    


   
</body>
</html>

templates/accounts/signup.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clarissa - sistema de IoT para monitoramento e cuidado de plantas caseiras</title>
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/minhas_plantas.css">
    <link rel="stylesheet" href="/static/signup.css">
</head>
<body>
    <div id="navbar">
        <div id="nav">
            <h1>Clarissa</h1>
        </div>
        <div id="left_bar">

            <p>
                <a href="/accounts/login" >Login</a>
            </p>

            <p>
                <a href="/accounts/signup" class="page">Criar conta</a>
            </p>
            
        </div>
        <div id="bottom_left"></div>
        
    </div>

    <div id="container" class="box" >
        <div id="small_table1">

            <h1>Criar novo usuário</h1>
            <form id="form" class="site-form" method="POST" action="/accounts/signup/">
                {% csrf_token %}
                {{form}}
                <p>
                    <input type="submit" value="Cadastrar">
                </p>
                
            </form>
        </div>

    </div>
    


   
</body>
</html>

templates/apagar.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="0; url=/minhas_plantas">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

templates/banco_de_dados.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clarissa - sistema de IoT para monitoramento e cuidado de plantas caseiras</title>
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/banco_de_dados.css">
</head>
<body>
    <div id="navbar">
        <div id="nav">
            <h1>Clarissa</h1>
        </div>
        <div id="left_bar">
            <a href="/nova_planta">Cadastrar nova planta </a>
            <p>
                <a href="/minhas_plantas" >Minhas plantas </a>
            </p>
            
            <p>
                <a href="/banco_de_dados" class="page">Banco de dados </a>
            </p>

            <p>
                <a href="/informacoes">Informações do sistema</a>
            </p>
            
            <p>
                <a href="/accounts/logout">Sair</a>
            </p>
            
            
        </div>
        <div id="bottom_left"></div>
        
    </div>

    <div id="container" class="box">
        <div id="small_table1">
            <table id="plantas">

                <tr>
                    <th>Nome comum</th>
                    <th>Espécie</th>
                    <th>Temperatura ideal</th>
                    <th>Horas de sol por dia</th>
                    <th>Regar a cada</th>
                    <th>Observações</th>
                </tr>

                    {% for item in bd %}
                    <tr>    
                        <td> {{item.nome_comum}} </td>
                        <td>{{item.nome_especie}}</td>
                        <td>{{item.temperatura}} °C</td>
                        <td>{{item.sol_horas}} hora</td>
                        <td>{{item.rega_dias}} dias</td>
                        <td>{{item.obs}}</td>
                    </tr>

                    {% endfor %}
                
            </table>

        </div>
    </div>
    
</body>
</html>

templates/dados_planta.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Clarissa - sistema de IoT para monitoramento e cuidado de plantas caseiras</title>
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/dados_planta.css">
</head>
<body onload='reload()'>
    <div id="navbar">
        <div id="nav">
            <h1>Clarissa</h1>
        </div>
        <div id="left_bar">
            <a href="/nova_planta">Cadastrar nova planta </a>
            <p>
                <a href="/minhas_plantas" class="page">Minhas plantas </a>
            </p>
            
            <p>
                <a href="/banco_de_dados">Banco de dados </a>
            </p>

            <p>
                <a href="/informacoes">Informações do sistema</a>
            </p>

            <p>
                <a href="/accounts/logout">Sair</a>
            </p>
            

            
            
        </div>
        <div id="bottom_left"></div>
        
    </div>

    <div id="container">

        {% for plant in planta %}

            
        {% for item in bd %}
       
        <div id="infos">
            <img src="/uploads/{{plant.image}}" alt="" id="img">
            <section id="square">
                <h2>Incidência Solar</h2>
                <h2 id="IncidenciaSolar">{{plant.incidencia_solar}}</h2>

                <h3>Ideal: {{item.sol_horas}} horas/dia</h3>
                <h3 id="atualizado"></h3>
            </section>

            <section id="square">
                <h2>Temperatura: </h2>
                <h2 id="Temperatura">{{plant.temperatura}}</h2>
                <h3>Ideal: {{item.temperatura}} °C</h3>
                <h3 id="atualizado"></h3>
            </section>

            <section id="square_special">
                <h2 id="nome">{{plant.name}}</h2>
                <h3 id="especie">Espécie: {{plant.species}}</h3>
                <h4 id="agp">Criada em: </h4>
                <h4 id="idade">{{plant.date}}</h4>
            </section>
            <section id="square">
                <h2>Umidade: </h2>
                <h2 id="Umidade">{{plant.umidade}}</h2>
                <h3 id="atualizado"></h3>
            </section>

            <section id="square">
                <h2>Regada em:</h2>
                <h3 id="Regada">{{plant.regada}}</h3>

                <h3 style="padding-top: 1rem;">Regar a cada {{item.rega_dias}} dias</h3>
                <h3></h3>
                <h3 id="atualizado"></h3>
            </section>

            {% endfor %}
            {% endfor %}

            <form id='form' class="site-form" action="/dados_planta/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="date" name="regada" value="" required='' id="id_regada">
                <button type="submit" id="btn_submit">Regar</button>
            </form>

            <section id='delete'>
                <a href="/deletar" >Deletar</a>
            </section>
            
        </div>
        

    </div>
    

</body>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="/static/dados_planta.js"></script>


</html>

templates/deletar.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="refresh" content="0; url=/minhas_plantas">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

templates/informacoes.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clarissa - sistema de IoT para monitoramento e cuidado de plantas caseiras</title>
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/informacoes.css">
</head>
<body>
    <div id="navbar">
        <div id="nav">
            <h1>Clarissa</h1>
        </div>
        <div id="left_bar">
            <a href="/nova_planta">Cadastrar nova planta </a>
            <p>
                <a href="/minhas_plantas" >Minhas plantas </a>
            </p>
            
            <p>
                <a href="/banco_de_dados" >Banco de dados </a>
            </p>

            <p>
                <a href="/informacoes" class="page">Informações do sistema</a>
            </p>

            <p>
                <a href="/accounts/logout">Sair</a>
            </p>
            
            
            
        </div>
        <div id="bottom_left"></div>
        
    </div>

    <div id="container">
        <div id="infos">
            <h1>Clarissa</h1>
            <p>
                <h3 style="padding-top: 1rem;">Versão: 1.0</h3>
                <h3 style="padding-top: 1rem;">Agradecimentos</h3>
                <h3 style="padding-top: 15rem">Todos os direitos reservados</h3>
            </p>
        </div>
    </div>
    
</body>
</html>

templates/minhas_plantas.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clarissa - sistema de IoT para monitoramento e cuidado de plantas caseiras</title>
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/minhas_plantas.css">
</head>
<body>
    <div id="navbar">
        <div id="nav">
            <h1>Clarissa</h1>
        </div>
        <div id="left_bar">
            <a href="/nova_planta">Cadastrar nova planta </a>
            <p>
                <a href="/minhas_plantas" class="page">Minhas plantas </a>
            </p>
            
            <p>
                <a href="/banco_de_dados">Banco de dados </a>
            </p>

            <p>
                <a href="/informacoes">Informações do sistema</a>
            </p>

            <p>
                <a href="/accounts/logout">Sair</a>
            </p>
            
            <p style="display: none;" id="user_id">
                {{form}}
            </p>
            
            
        </div>
        <div id="bottom_left"></div>
        
    </div>
    
    <div id="container" class="box">
        <h2 style="color: white">Plantas de {{ user }}</h2>
        <div id='square_table'>
            <table id="plantas">

                <tr>
                    <th>Nome</th>
                    <th>Espécie</th>
                    <th>Data de plantio</th>
                    <th>Link</th>
                </tr>

                    {% for planta in plantas %}
                    <tr>    
                        <td> {{planta.name}} </td>
                        <td>{{planta.species}}</td>
                        <td>{{planta.date}}</td>
                        <td><a href="/dados_planta" onclick=' dadosPage("{{planta.name}}")'>Ir</a></td>
                    </tr>

                    {% endfor %}
                
            </table>
        </div>
        <a id="apagar_tudo" onclick="" href="/apagar">Apagar todas as plantas</a>
    



    </div>
    


    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="/static/minhas_plantas.js"></script>
   
</body>
</html>

templates/nova_planta.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clarissa - sistema de IoT para monitoramento e cuidado de plantas caseiras</title>
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/nova_planta.css">

</head>
<body>
    <div id="navbar">
        <div id="nav">
            <h1>Clarissa</h1>
        </div>
        <div id="left_bar">
            <a href="/nova_planta" class="page">Cadastrar nova planta </a>
            <a href="/minhas_plantas">
                Minhas plantas 
                <div id="plants">

                </div>
            </a>
            <a href="/banco_de_dados">
                Banco de dados 
                <div id="bd">

                </div>
            </a>
            <a href="/informacoes">Informações do sistema</a>

            <p>
                <a href="/accounts/logout">Sair</a>
            </p>
            
            
            
        </div>
        <div id="bottom_left"></div>

        
    </div>
    <div id="container" class="box">
        <div>
            
            <p id="title">Adicionar planta</p>
            <form id='form' class="site-form" action="/nova_planta/" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <label for="id_name"><p id="tips">Nome da planta</p> </label><input type="text" placeholder="Nome da planta" name="name" maxlength="300" required="" id="id_name">
                <label for="id_species"><p id="tips">Nome da espécie</p></label>
                <select name="species" maxlength="300" required="" id="id_species">
                  <option value="">Nome da espécie</option>
                  {% for item in bd %}
                  <option value="{{item.nome_comum}}">{{item.nome_comum}}</option>
                  {% endfor %}
                </select>
                <label for="id_date"><p id="tips">Data do plantio</p></label><input type="date" name="date" value='' required="" id="id_date">
                <label for="id_image"><p id="tips">Foto (opcional)</p></label><input type="file" name="image" accept="image/*" id="id_image">
                <p>
                    <button type="submit" id="btn" >Criar planta</button>
                </p>
                <script>
                    let message='{{message}}'
                    if (message != '')
                        alert('{{ message }}');
                </script>
                
            </form>

        </div>
    </div>



    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="/static/nova_planta.js"></script>

</body>

</html>

templates/qrcode.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clarissa - sistema de IoT para monitoramento e cuidado de plantas caseiras</title>
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/minhas_plantas.css">
</head>
<body>
    <div id="navbar">
        <div id="nav">
            <h1>Clarissa</h1>
        </div>
        <div id="left_bar">
            <a href="/nova_planta">Cadastrar nova planta </a>
            <p>
                <a href="/minhas_plantas" >Minhas plantas </a>
            </p>

            <p>
                <a href="/banco_de_dados">Banco de dados </a>
            </p>

            <p>
                <a href="/informacoes">Informações do sistema</a>
            </p>

            <p>
                <a href="/accounts/logout">Sair</a>
            </p>

            <p style="display: none;" id="user_id">
                {{form}}
            </p>


        </div>
        <div id="bottom_left"></div>

    </div>

    <div id="container" class="box">
        <h1>
            Salve os dados da sua planta num QRCODE
        </h1>

        <img id="imageQRCode" src="">

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script>
            let planta='{{ planta }}'
            if (planta != '')
                var conteudo = 'Oi, eu me chamo {{planta}}, sou um(a) {{ especie }} e meu pai/mãe é {{ usuario }} '

            else {
                var conteudo='Crie uma planta primeiro'
            }
            var GoogleCharts = 'https://chart.googleapis.com/chart?chs=500x500&cht=qr&chl=';
            var imagemQRCode = GoogleCharts + conteudo;
            $('#imageQRCode').attr('src', imagemQRCode);

        </script>
    </div>